Add optional node container target to Portal
reach/reach-ui pull request #756
Opened 2021-03-02 13:48 UTC by Warsaken

This PR aims to solve the issue #666.

It introduces a new optional prop for Portal: `nodeContainer` that allows the user to specify the containing node to render the Portal in.

If this PR is approved, then we can create a follow up PR to pass this prop to other relevant packages.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [ ] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [x] Ensure formatting is consistent with the project's Prettier configuration.
- [x] Add documentation to support any new features.

This pull request:

- [ ] Creates a new package
- [ ] Fixes a bug in an existing package
- [x] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [ ] Other

2021-03-29 23:59 UTC, chaance requested changes
Thanks for the PR! A few changes requested but I'd like to merge this when we can.

2021-03-29 23:59 UTC, chaance commented on packages/portal/src/index.tsx
> +  nodeContainer,
Can we rename this prop to simply `container`?

2021-03-29 23:59 UTC, chaance commented on packages/portal/src/index.tsx
> +    const container = nodeContainer || portalNode.current!.ownerDocument.body;
I think we can simplify this a tiny bit

```
let body = container || ownerDocument.body
body.appendChild(portalNode.current)
```

2021-03-29 23:59 UTC, chaance commented on packages/portal/src/index.tsx
> +  nodeContainer?: HTMLElement;
Let's make `container` of type `Node`, `Document` is the default and really is can be any Node type.

2021-03-29 23:59 UTC, chaance commented on website/src/pages/portal.mdx
> +| [`nodeContainer`](#nodeContainer) | HTMLElement | false    |
Update the prop name and type here as well!

2021-03-29 23:59 UTC, chaance commented on website/src/pages/portal.mdx
> +The DOM element container of the portal. If not set the portal will be appended to the body of the document.
Update the prop name and type here as well, and tweak to read "The DOM **node** container..."

2021-04-01 12:55 UTC, Warsaken commented
@chaance thanks for reviewing, I made the requested changes now.

2021-04-01 17:24 UTC, chaance commented
On second thought I think it makes a lot more sense for this prop to accept a ref rather than a DOM node. Probably requested changes before I thought about it more fully, so sorry about that. Let's hold for right now, I'll circle back to this after I've taken care of a few high-priority bugs for the next release.

2021-04-19 01:45 UTC, Warsaken commented
>  On second thought I think it makes a lot more sense for this prop to accept a ref rather than a DOM node. Probably requested changes before I thought about it more fully, so sorry about that. Let's hold for right now, I'll circle back to this after I've taken care of a few high-priority bugs for the next release.

Several of the other libraries I encountered write it as an `HTMLElement` (e.g.: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/portal/portal.tsx) that's why I started with that type, since it's familiar and easy to migrate existing code to Reach later. But let me know which type you think is the best here and I can make those changes.

2021-08-15 23:49 UTC, Warsaken commented
@chaance This has been here for a while so I went ahead and updated the type to a `ref` like you suggested.

Being of `node` type or `HTMLElement` also seemed reasonable to me, for example in my use case the container I need to append the portal to is obtained through a function that returns a `HTMLElement` which may not even be a react component.
But either way works, I just need to convert that to the ref format afterwards.

Let me know if there are any other changes necessary. Thanks.

2021-08-30 14:46 UTC, zefj commented
hey @chaance , we could really use this feature too. Our case involves `menu-button` within overflow: hidden nodes living within modals, so unfortunately we cannot just disable the portal :disappointed: Is there any chance of getting this soon?

2021-09-04 15:54 UTC, chaance approved these changes

2021-09-04 16:12 UTC, merged

2021-09-04 20:11 UTC, Warsaken commented
I see the PR was merged, thanks @chaance.

Now we need to create a PR to pass the props along for the other libraries that use Portal (e.g. Dialog).
Will you, or someone else, create a PR for that or should I do it?